export const projects = [
  {
    id: 1,
    title: "E-Commerce Platform",
    description:
      "A full-featured e-commerce platform with product management, cart functionality, user authentication, and payment processing.",
    image: "/ss4.png",
    tags: ["MongoDB", "Express", "React", "Node.js", "JWT", "Stripe", "emailjs"],
    liveLink: "#",
    githubLink: "#",
    featured: true,
  },
  {
    id: 2,
    title: "Task Management App",
    description:
      "A collaborative task management application with real-time updates, team workspaces, and progress tracking.",
    image: "/ss3.png",
    tags: ["MongoDB", "Express", "React", "Node.js", "JWT"],
    liveLink: "#",
    githubLink: "#",
    featured: true,
  },
  {
    id: 3,
    title: "Social Media Dashboard",
    description: "A dashboard that aggregates and displays social media metrics and analytics from multiple platforms.",
    image: "/ss2.png",
    tags: ["MongoDB", "Express", "React", "Node.js"],
    liveLink: "#",
    githubLink: "#",
    featured: false,
  },
  {
    id: 4,
    title: "Real Estate Listing Platform",
    description: "A platform for property listings with advanced search, filtering, and user favorites.",
    image: "/ss1.png",
    tags: ["MongoDB", "Express", "React", "Node.js", "Google Maps API"],
    liveLink: "#",
    githubLink: "#",
    featured: false,
  },
  {
    id: 5,
    title: "Blog CMS",
    description: "A content management system for blogs with markdown support, categories, and user management.",
    image: "/placeholder.svg?height=600&width=800",
    tags: ["MongoDB", "Express", "React", "Node.js", "Markdown"],
    liveLink: "#",
    githubLink: "#",
    featured: false,
  },
  // {
  //   id: 6,
  //   title: "Weather Application",
  //   description: "A weather application that provides current conditions and forecasts based on location.",
  //   image: "/placeholder.svg?height=600&width=800",
  //   tags: ["MongoDB", "Express", "React", "Node.js", "Weather API"],
  //   liveLink: "#",
  //   githubLink: "#",
  //   featured: false,
  // },
]